# This is a basic workflow to help you get started with Actions

name: Schemaspy

on:
  push:
    branches:
      - master # Changing the branch here would also work

jobs:
  schemaspy:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_PASSWORD: secret
          TZ: Asia/Tokyo
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install composer dependencies
      run: |
        composer install --no-scripts
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
        php artisan migrate:refresh --seed
    - name: Run schemaspy
      run: |
        docker run -v "./docs/schema/output" --net="host" schemaspy/schemaspy:latest -t mysql -host $DB_HOST:3306 -db $DB_DATABASE -u $DB_USERNAME -p $DB_PASSWORD -connprops useSSL\\=false -s $DB_DATABASE
      env:
        DB_HOST: 127.0.0.1
        DB_DATABASE: testing
        DB_USERNAME: root
        DB_PASSWORD: secret

    - uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: "Generate Schemaspy Docs"
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}